#!/bin/sh
#copyright by hiboy
source /etc/storage/script/init.sh

link="Advanced_Extensions_adbyby.asp"
echo $1
if [ "$1"x = "stop"x ] ; then
    nvram set adbyby_enable=0
    exit
fi

eval 'nvram set tablink'$1'='$link';'

nvram set adbyby_L2="$(($3 + 10))"
nvram set adbyby_L3="$2"
#     show_menu(8,<% nvram_get_x("", "adbyby_L2"); %>,<% nvram_get_x("", "adbyby_L3"); %>);

