#!/bin/sh
#copyright by hiboy
source /etc/storage/script/init.sh

link="Advanced_Extensions_app26.asp"
echo $1
if [ "$1"x = "stop"x ] ; then
    nvram set app_139=0 #caddy_enable
    exit
fi

if [ "$1" != "del" ] ; then
eval 'nvram set tablink'$1'='$link';'

nvram set caddy_L2="$(($3 + 10))"
nvram set caddy_L3="$2"
#     show_menu(8,<% nvram_get_x("", "caddy_L2"); %>,<% nvram_get_x("", "caddy_L3"); %>);
fi

get_www ()
{

# 加载程序配置页面
mkdir -p /opt/app/caddy
if [ ! -f "/opt/app/caddy/Advanced_Extensions_caddy.asp" ] || [ ! -s "/opt/app/caddy/Advanced_Extensions_caddy.asp" ] ; then
	wgetcurl.sh /opt/app/caddy/Advanced_Extensions_caddy.asp "$hiboyfile/Advanced_Extensions_caddyasp" "$hiboyfile2/Advanced_Extensions_caddyasp"
fi
umount /www/Advanced_Extensions_app26.asp
if [ -f "/opt/app/caddy/Advanced_Extensions_caddy.asp" ] ; then
	mount --bind /opt/app/caddy/Advanced_Extensions_caddy.asp /www/Advanced_Extensions_app26.asp
	app26_ver=$(grep 'app26_ver=' /opt/app/caddy/Advanced_Extensions_caddy.asp | awk -F '=' '{print $2;}')
	nvram set app26_ver=${app26_ver}
fi

}

get_app ()
{

# 更新程序启动脚本
[ "$1" = "del" ] && rm -rf /etc/storage/script/Sh87_cad_dy.sh
if [ ! -f "/etc/storage/script/Sh87_cad_dy.sh" ] || [ ! -s "/etc/storage/script/Sh87_cad_dy.sh" ] ; then
	wgetcurl.sh /etc/storage/script/Sh87_cad_dy.sh "$hiboyscript/script/Sh87_cad_dy.sh" "$hiboyscript/script/Sh87_cad_dy.sh"
fi
chmod 777 /etc/storage/script -R
if [ ! -f "/etc/storage/app_11.sh" ] || [ ! -s "/etc/storage/app_11.sh" ] ; then
/etc/storage/script/Sh87_cad_dy.sh update_app
fi

[ "$1" = "del" ] && exit

}

if [ -f /tmp/webui_yes ] ; then
get_www &
get_app $1 &
[ "$1" = "del" ] && exit
fi

