#!/bin/sh
#copyright by hiboy
source /etc/storage/script/init.sh

link="Advanced_Extensions_CloudXNS.asp"
echo $1
if [ "$1"x = "stop"x ] ; then
    nvram set cloudxns_enable=0
    exit
fi

eval 'nvram set tablink'$1'='$link';'

nvram set cloudxns_L2="$(($3 + 10))"
nvram set cloudxns_L3="$2"
#     show_menu(8,<% nvram_get_x("", "cloudxns_L2"); %>,<% nvram_get_x("", "cloudxns_L3"); %>);

