#!/bin/bash
#copyright by hiboy
source /etc/storage/script/init.sh

link="Advanced_Extensions_app16.asp"
echo $1
if [ "$1"x = "stop"x ] ; then
    nvram set app_64=0 #ddnsto_enable
    exit
fi

if [ "$1" != "del" ] ; then
eval 'nvram set tablink'$1'='$link';'

nvram set ddnsto_L2="$(($3 + 10))"
nvram set ddnsto_L3="$2"
#     show_menu(8,<% nvram_get_x("", "ddnsto_L2"); %>,<% nvram_get_x("", "ddnsto_L3"); %>);
fi

get_www ()
{

# 加载程序配置页面
mkdir -p /opt/app/ddnsto
if [ -f "/tmp/www_asp/Advanced_Extensions_ddnstoasp" ] ; then
if [ ! -f "/opt/app/ddnsto/Advanced_Extensions_ddnsto.asp" ] ; then
	mv -f /tmp/www_asp/Advanced_Extensions_ddnstoasp /opt/app/ddnsto/Advanced_Extensions_ddnsto.asp
else
	rm -f /tmp/www_asp/Advanced_Extensions_ddnstoasp
fi
fi
if [ ! -f "/opt/app/ddnsto/Advanced_Extensions_ddnsto.asp" ] || [ ! -s "/opt/app/ddnsto/Advanced_Extensions_ddnsto.asp" ] ; then
	wgetcurl.sh /opt/app/ddnsto/Advanced_Extensions_ddnsto.asp "$hiboyfile/Advanced_Extensions_ddnstoasp" "$hiboyfile2/Advanced_Extensions_ddnstoasp"
fi
umount /www/Advanced_Extensions_app16.asp
if [ -f "/opt/app/ddnsto/Advanced_Extensions_ddnsto.asp" ] ; then
	mount --bind /opt/app/ddnsto/Advanced_Extensions_ddnsto.asp /www/Advanced_Extensions_app16.asp
	app16_ver=$(grep 'app16_ver=' /opt/app/ddnsto/Advanced_Extensions_ddnsto.asp | awk -F '=' '{print $2;}')
	nvram set app16_ver=${app16_ver}
fi

}

get_app ()
{

# 更新程序启动脚本
[ "$1" = "del" ] && rm -rf /etc/storage/script/Sh90_ddns_to.sh
if [ ! -f "/etc/storage/script/Sh90_ddns_to.sh" ] || [ ! -s "/etc/storage/script/Sh90_ddns_to.sh" ] ; then
	wgetcurl.sh /etc/storage/script/Sh90_ddns_to.sh "$hiboyscript/script/Sh90_ddns_to.sh" "$hiboyscript/script/Sh90_ddns_to.sh"
fi
chmod 777 /etc/storage/script -R

[ "$1" = "del" ] && exit

}

if [ -f /tmp/webui_yes ] ; then
get_www &
get_app $1 &
[ "$1" = "del" ] && exit
fi

