#!/bin/sh
#copyright by hiboy
source /etc/storage/script/init.sh

link="Advanced_Extensions_app25.asp"
echo $1
if [ "$1"x = "stop"x ] ; then
    nvram set app_45=0 #ddnsgo_enable
    exit
fi

if [ "$1" != "del" ] ; then
eval 'nvram set tablink'$1'='$link';'

nvram set ddnsgo_L2="$(($3 + 10))"
nvram set ddnsgo_L3="$2"
#     show_menu(8,<% nvram_get_x("", "ddnsgo_L2"); %>,<% nvram_get_x("", "ddnsgo_L3"); %>);
fi

get_www ()
{

# 加载程序配置页面
mkdir -p /opt/app/ddnsgo
if [ ! -f "/opt/app/ddnsgo/Advanced_Extensions_ddnsgo.asp" ] || [ ! -s "/opt/app/ddnsgo/Advanced_Extensions_ddnsgo.asp" ] ; then
	wgetcurl.sh /opt/app/ddnsgo/Advanced_Extensions_ddnsgo.asp "$hiboyfile/Advanced_Extensions_ddnsgoasp" "$hiboyfile2/Advanced_Extensions_ddnsgoasp"
fi
umount /www/Advanced_Extensions_app25.asp
if [ -f "/opt/app/ddnsgo/Advanced_Extensions_ddnsgo.asp" ] ; then
	mount --bind /opt/app/ddnsgo/Advanced_Extensions_ddnsgo.asp /www/Advanced_Extensions_app25.asp
	app25_ver=$(grep 'app25_ver=' /opt/app/ddnsgo/Advanced_Extensions_ddnsgo.asp | awk -F '=' '{print $2;}')
	nvram set app25_ver=${app25_ver}
fi

}

get_app ()
{

# 更新程序启动脚本
[ "$1" = "del" ] && rm -rf /etc/storage/script/Sh88_ddns_go.sh
if [ ! -f "/etc/storage/script/Sh88_ddns_go.sh" ] || [ ! -s "/etc/storage/script/Sh88_ddns_go.sh" ] ; then
	wgetcurl.sh /etc/storage/script/Sh88_ddns_go.sh "$hiboyscript/script/Sh88_ddns_go.sh" "$hiboyscript/script/Sh88_ddns_go.sh"
fi
chmod 777 /etc/storage/script -R
if [ ! -f "/etc/storage/app_35.sh" ] || [ ! -s "/etc/storage/app_35.sh" ] ; then
/etc/storage/script/Sh88_ddns_go.sh update_app
fi

[ "$1" = "del" ] && exit

}

if [ -f /tmp/webui_yes ] ; then
get_www &
get_app $1 &
[ "$1" = "del" ] && exit
fi

