#!/bin/sh
#copyright by hiboy
source /etc/storage/script/init.sh

link="Advanced_Extensions_frp.asp"
echo $1
if [ "$1"x = "stop"x ] ; then
    nvram set frp_enable=0
    exit
fi

eval 'nvram set tablink'$1'='$link';'

nvram set frp_L2="$(($3 + 10))"
nvram set frp_L3="$2"
#     show_menu(8,<% nvram_get_x("", "frp_L2"); %>,<% nvram_get_x("", "frp_L3"); %>);

