#!/bin/bash
#copyright by hiboy
source /etc/storage/script/init.sh

link="Advanced_Extensions_app23.asp"
echo $1
if [ "$1"x = "stop"x ] ; then
    nvram set app_133=0 #gocryptfs_enable
    exit
fi

if [ "$1" != "del" ] ; then
eval 'nvram set tablink'$1'='$link';'

nvram set gocryptfs_L2="$(($3 + 10))"
nvram set gocryptfs_L3="$2"
#     show_menu(8,<% nvram_get_x("", "gocryptfs_L2"); %>,<% nvram_get_x("", "gocryptfs_L3"); %>);
fi

get_www ()
{

# 加载程序配置页面
mkdir -p /opt/app/gocryptfs
if [ -f "/tmp/www_asp/Advanced_Extensions_gocryptfsasp" ] ; then
if [ ! -f "/opt/app/gocryptfs/Advanced_Extensions_gocryptfs.asp" ] ; then
	mv -f /tmp/www_asp/Advanced_Extensions_gocryptfsasp /opt/app/gocryptfs/Advanced_Extensions_gocryptfs.asp
else
	rm -f /tmp/www_asp/Advanced_Extensions_gocryptfsasp
fi
fi
if [ ! -f "/opt/app/gocryptfs/Advanced_Extensions_gocryptfs.asp" ] || [ ! -s "/opt/app/gocryptfs/Advanced_Extensions_gocryptfs.asp" ] ; then
	wgetcurl.sh /opt/app/gocryptfs/Advanced_Extensions_gocryptfs.asp "$hiboyfile/Advanced_Extensions_gocryptfsasp" "$hiboyfile2/Advanced_Extensions_gocryptfsasp"
fi
umount /www/Advanced_Extensions_app23.asp
if [ -f "/opt/app/gocryptfs/Advanced_Extensions_gocryptfs.asp" ] ; then
	mount --bind /opt/app/gocryptfs/Advanced_Extensions_gocryptfs.asp /www/Advanced_Extensions_app23.asp
	app23_ver=$(grep 'app23_ver=' /opt/app/gocryptfs/Advanced_Extensions_gocryptfs.asp | awk -F '=' '{print $2;}')
	nvram set app23_ver=${app23_ver}
fi

}

get_app ()
{

# 更新程序启动脚本
[ "$1" = "del" ] && rm -rf /etc/storage/script/Sh05_go_cryptfs.sh
if [ ! -f "/etc/storage/script/Sh05_go_cryptfs.sh" ] || [ ! -s "/etc/storage/script/Sh05_go_cryptfs.sh" ] ; then
	wgetcurl.sh /etc/storage/script/Sh05_go_cryptfs.sh "$hiboyscript/script/Sh05_go_cryptfs.sh" "$hiboyscript/script/Sh05_go_cryptfs.sh"
fi
chmod 777 /etc/storage/script -R
if [ ! -f "/etc/storage/app_17.sh" ] || [ ! -s "/etc/storage/app_17.sh" ] || [ ! -f "/etc/storage/app_32.sh" ] || [ ! -s "/etc/storage/app_32.sh" ] ; then
/etc/storage/script/Sh05_go_cryptfs.sh update_app
fi

[ "$1" = "del" ] && exit

}

if [ -f /tmp/webui_yes ] ; then
get_www &
get_app $1 &
[ "$1" = "del" ] && exit
fi

