#!/bin/bash
#copyright by hiboy
source /etc/storage/script/init.sh

link="Advanced_Extensions_app09.asp"
echo $1
if [ "$1"x = "stop"x ] ; then
    nvram set app_26=0 #guestkit_enable
    exit
fi

if [ "$1" != "del" ] ; then
eval 'nvram set tablink'$1'='$link';'

nvram set guestkit_L2="$(($3 + 10))"
nvram set guestkit_L3="$2"
#     show_menu(8,<% nvram_get_x("", "guestkit_L2"); %>,<% nvram_get_x("", "guestkit_L3"); %>);
fi

get_www ()
{

# 加载程序配置页面
mkdir -p /opt/app/guestkit
if [ -f "/tmp/www_asp/Advanced_Extensions_guestkitasp" ] ; then
if [ ! -f "/opt/app/guestkit/Advanced_Extensions_guestkit.asp" ] ; then
	mv -f /tmp/www_asp/Advanced_Extensions_guestkitasp /opt/app/guestkit/Advanced_Extensions_guestkit.asp
else
	rm -f /tmp/www_asp/Advanced_Extensions_guestkitasp
fi
fi
if [ ! -f "/opt/app/guestkit/Advanced_Extensions_guestkit.asp" ] || [ ! -s "/opt/app/guestkit/Advanced_Extensions_guestkit.asp" ] ; then
	wgetcurl.sh /opt/app/guestkit/Advanced_Extensions_guestkit.asp "$hiboyfile/Advanced_Extensions_guestkitasp" "$hiboyfile2/Advanced_Extensions_guestkitasp"
fi
umount /www/Advanced_Extensions_app09.asp
if [ -f "/opt/app/guestkit/Advanced_Extensions_guestkit.asp" ] ; then
	mount --bind /opt/app/guestkit/Advanced_Extensions_guestkit.asp /www/Advanced_Extensions_app09.asp
	app9_ver=$(grep 'app9_ver=' /opt/app/guestkit/Advanced_Extensions_guestkit.asp | awk -F '=' '{print $2;}')
	nvram set app9_ver=${app9_ver}
fi

}

get_app ()
{

# 更新程序启动脚本
[ "$1" = "del" ] && rm -rf /etc/storage/script/Sh28_guest_kit.sh
if [ ! -f "/etc/storage/script/Sh28_guest_kit.sh" ] || [ ! -s "/etc/storage/script/Sh28_guest_kit.sh" ] ; then
	wgetcurl.sh /etc/storage/script/Sh28_guest_kit.sh "$hiboyscript/script/Sh28_guest_kit.sh" "$hiboyscript/script/Sh28_guest_kit.sh"
fi
chmod 777 /etc/storage/script -R
# if [ ! -f "/etc/storage/app_8.sh" ] || [ ! -s "/etc/storage/app_8.sh" ] ; then
# /etc/storage/script/Sh28_guest_kit.sh update_app
# fi

[ "$1" = "del" ] && exit

}

if [ -f /tmp/webui_yes ] ; then
get_www &
get_app $1 &
[ "$1" = "del" ] && exit
fi

