#!/bin/sh
#copyright by hiboy
source /etc/storage/script/init.sh

link="Advanced_Extensions_MEOW.asp"
echo $1
if [ "$1"x = "stop"x ] ; then
    nvram set meow_enable=0
    exit
fi

eval 'nvram set tablink'$1'='$link';'

nvram set meow_L2="$(($3 + 10))"
nvram set meow_L3="$2"
#     show_menu(8,<% nvram_get_x("", "meow_L2"); %>,<% nvram_get_x("", "meow_L3"); %>);

