#!/bin/sh
#copyright by hiboy
source /etc/storage/script/init.sh

link="Advanced_Extensions_SS_list.asp"
echo $1
if [ "$1"x = "stop"x ] ; then
    #nvram set SS_list=0
    exit
fi

eval 'nvram set tablink'$1'='$link';'

nvram set SS_list_L2="$(($3 + 10))"
nvram set SS_list_L3="$2"
#     show_menu(8,<% nvram_get_x("", "SS_list_L2"); %>,<% nvram_get_x("", "SS_list_L3"); %>);

