#!/bin/bash
#copyright by hiboy
source /etc/storage/script/init.sh

link="Advanced_Extensions_app12.asp"
echo $1
if [ "$1"x = "stop"x ] ; then
    nvram set app_46=0 #tgbot_enable
    exit
fi

if [ "$1" != "del" ] ; then
eval 'nvram set tablink'$1'='$link';'

nvram set tgbot_L2="$(($3 + 10))"
nvram set tgbot_L3="$2"
#     show_menu(8,<% nvram_get_x("", "tgbot_L2"); %>,<% nvram_get_x("", "tgbot_L3"); %>);
fi

get_www ()
{

# 加载程序配置页面
mkdir -p /opt/app/tgbot
if [ -f "/tmp/www_asp/Advanced_Extensions_tgbotasp" ] ; then
if [ ! -f "/opt/app/tgbot/Advanced_Extensions_tgbot.asp" ] ; then
	mv -f /tmp/www_asp/Advanced_Extensions_tgbotasp /opt/app/tgbot/Advanced_Extensions_tgbot.asp
else
	rm -f /tmp/www_asp/Advanced_Extensions_tgbotasp
fi
fi
if [ ! -f "/opt/app/tgbot/Advanced_Extensions_tgbot.asp" ] || [ ! -s "/opt/app/tgbot/Advanced_Extensions_tgbot.asp" ] ; then
	wgetcurl.sh /opt/app/tgbot/Advanced_Extensions_tgbot.asp "$hiboyfile/Advanced_Extensions_tgbotasp" "$hiboyfile2/Advanced_Extensions_tgbotasp"
fi
umount /www/Advanced_Extensions_app12.asp
if [ -f "/opt/app/tgbot/Advanced_Extensions_tgbot.asp" ] ; then
	mount --bind /opt/app/tgbot/Advanced_Extensions_tgbot.asp /www/Advanced_Extensions_app12.asp
	app12_ver=$(grep 'app12_ver=' /opt/app/tgbot/Advanced_Extensions_tgbot.asp | awk -F '=' '{print $2;}')
	nvram set app12_ver=${app12_ver}
fi

}

get_app ()
{

# 更新程序启动脚本
[ "$1" = "del" ] && rm -rf /etc/storage/script/Sh50_tg_bot.sh
if [ ! -f "/etc/storage/script/Sh50_tg_bot.sh" ] || [ ! -s "/etc/storage/script/Sh50_tg_bot.sh" ] ; then
	wgetcurl.sh /etc/storage/script/Sh50_tg_bot.sh "$hiboyscript/script/Sh50_tg_bot.sh" "$hiboyscript/script/Sh50_tg_bot.sh"
fi
chmod 777 /etc/storage/script -R
if [ ! -f "/etc/storage/app_10.sh" ] || [ ! -s "/etc/storage/app_10.sh" ] ; then
/etc/storage/script/Sh50_tg_bot.sh update_app
fi

[ "$1" = "del" ] && exit

}

if [ -f /tmp/webui_yes ] ; then
get_www &
get_app $1 &
[ "$1" = "del" ] && exit
fi

