#!/bin/bash
#copyright by hiboy
source /etc/storage/script/init.sh

link="Advanced_Extensions_app13.asp"
echo $1
if [ "$1"x = "stop"x ] ; then
    nvram set app_55=0 #tmall_enable
    exit
fi

if [ "$1" != "del" ] ; then
eval 'nvram set tablink'$1'='$link';'

nvram set tmall_L2="$(($3 + 10))"
nvram set tmall_L3="$2"
#     show_menu(8,<% nvram_get_x("", "tmall_L2"); %>,<% nvram_get_x("", "tmall_L3"); %>);
fi

get_www ()
{

# 加载程序配置页面
mkdir -p /opt/app/tmall
if [ -f "/tmp/www_asp/Advanced_Extensions_tmallasp" ] ; then
if [ ! -f "/opt/app/tmall/Advanced_Extensions_tmall.asp" ] ; then
	mv -f /tmp/www_asp/Advanced_Extensions_tmallasp /opt/app/tmall/Advanced_Extensions_tmall.asp
else
	rm -f /tmp/www_asp/Advanced_Extensions_tmallasp
fi
fi
if [ ! -f "/opt/app/tmall/Advanced_Extensions_tmall.asp" ] || [ ! -s "/opt/app/tmall/Advanced_Extensions_tmall.asp" ] ; then
	wgetcurl.sh /opt/app/tmall/Advanced_Extensions_tmall.asp "$hiboyfile/Advanced_Extensions_tmallasp" "$hiboyfile2/Advanced_Extensions_tmallasp"
fi
umount /www/Advanced_Extensions_app13.asp
if [ -f "/opt/app/tmall/Advanced_Extensions_tmall.asp" ] ; then
	mount --bind /opt/app/tmall/Advanced_Extensions_tmall.asp /www/Advanced_Extensions_app13.asp
	app13_ver=$(grep 'app13_ver=' /opt/app/tmall/Advanced_Extensions_tmall.asp | awk -F '=' '{print $2;}')
	nvram set app13_ver=${app13_ver}
fi

}

get_app ()
{

# 更新程序启动脚本
[ "$1" = "del" ] && rm -rf /etc/storage/script/Sh63_t_mall.sh
if [ ! -f "/etc/storage/script/Sh63_t_mall.sh" ] || [ ! -s "/etc/storage/script/Sh63_t_mall.sh" ] ; then
	wgetcurl.sh /etc/storage/script/Sh63_t_mall.sh "$hiboyscript/script/Sh63_t_mall.sh" "$hiboyscript/script/Sh63_t_mall.sh"
fi
chmod 777 /etc/storage/script -R
if [ ! -f "/etc/storage/app_13.sh" ] || [ ! -s "/etc/storage/app_13.sh" ] || [ ! -f "/etc/storage/app_14.sh" ] || [ ! -s "/etc/storage/app_14.sh" ] ; then
/etc/storage/script/Sh63_t_mall.sh update_app
fi

[ "$1" = "del" ] && exit

}

if [ -f /tmp/webui_yes ] ; then
get_www &
get_app $1 &
[ "$1" = "del" ] && exit
fi

