#!/bin/sh
#copyright by hiboy
source /etc/storage/script/init.sh

link="Advanced_Extensions_app11.asp"
echo $1
if [ "$1"x = "stop"x ] ; then
    nvram set app_44=0 #translate_enable
    exit
fi

if [ "$1" != "del" ] ; then
eval 'nvram set tablink'$1'='$link';'

nvram set translate_L2="$(($3 + 10))"
nvram set translate_L3="$2"
#     show_menu(8,<% nvram_get_x("", "translate_L2"); %>,<% nvram_get_x("", "translate_L3"); %>);
fi

get_www ()
{

# 加载程序配置页面
mkdir -p /opt/app/translate
if [ ! -f "/opt/app/translate/Advanced_Extensions_translate.asp" ] || [ ! -s "/opt/app/translate/Advanced_Extensions_translate.asp" ] ; then
	wgetcurl.sh /opt/app/translate/Advanced_Extensions_translate.asp "$hiboyfile/Advanced_Extensions_translateasp" "$hiboyfile2/Advanced_Extensions_translateasp"
fi
umount /www/Advanced_Extensions_app11.asp
if [ -f "/opt/app/translate/Advanced_Extensions_translate.asp" ] ; then
	mount --bind /opt/app/translate/Advanced_Extensions_translate.asp /www/Advanced_Extensions_app11.asp
	app11_ver=$(grep 'app11_ver=' /opt/app/translate/Advanced_Extensions_translate.asp | awk -F '=' '{print $2;}')
	nvram set app11_ver=${app11_ver}
fi

}

get_app ()
{

# 更新程序启动脚本
[ "$1" = "del" ] && rm -rf /opt/app/translate/*
if [ ! -f "/etc/storage/script/Sh59_trans_late.sh" ] || [ ! -s "/etc/storage/script/Sh59_trans_late.sh" ] ; then
	wgetcurl.sh /etc/storage/script/Sh59_trans_late.sh "$hiboyscript/script/Sh59_trans_late.sh" "$hiboyscript/script/Sh59_trans_late.sh"
fi
chmod 777 /etc/storage/script -R

[ "$1" = "del" ] && exit

}

if [ -f /tmp/webui_yes ] ; then
get_www &
get_app $1 &
[ "$1" = "del" ] && exit
fi

