#!/bin/bash
#copyright by hiboy
source /etc/storage/script/init.sh

link="Advanced_Extensions_app29.asp"
echo $1
if [ "$1"x = "stop"x ] ; then
    nvram set app_146=0 #v2raya_enable
    exit
fi

if [ "$1" != "del" ] ; then
eval 'nvram set tablink'$1'='$link';'

nvram set v2raya_L2="$(($3 + 10))"
nvram set v2raya_L3="$2"
#     show_menu(8,<% nvram_get_x("", "v2raya_L2"); %>,<% nvram_get_x("", "v2raya_L3"); %>);
fi

get_www ()
{

# 加载程序配置页面
mkdir -p /opt/app/v2raya
if [ ! -f "/opt/app/v2raya/Advanced_Extensions_v2raya.asp" ] || [ ! -s "/opt/app/v2raya/Advanced_Extensions_v2raya.asp" ] ; then
	wgetcurl.sh /opt/app/v2raya/Advanced_Extensions_v2raya.asp "$hiboyfile/Advanced_Extensions_v2rayaasp" "$hiboyfile2/Advanced_Extensions_v2rayaasp"
fi
umount /www/Advanced_Extensions_app29.asp
if [ -f "/opt/app/v2raya/Advanced_Extensions_v2raya.asp" ] ; then
	mount --bind /opt/app/v2raya/Advanced_Extensions_v2raya.asp /www/Advanced_Extensions_app29.asp
	app29_ver=$(grep 'app29_ver=' /opt/app/v2raya/Advanced_Extensions_v2raya.asp | awk -F '=' '{print $2;}')
	nvram set app29_ver=${app29_ver}
fi

}

get_app ()
{

# 更新程序启动脚本
[ "$1" = "del" ] && rm -rf /etc/storage/script/Sh84_v2raya.sh
if [ ! -f "/etc/storage/script/Sh84_v2raya.sh" ] || [ ! -s "/etc/storage/script/Sh84_v2raya.sh" ] ; then
	wgetcurl.sh /etc/storage/script/Sh84_v2raya.sh "$hiboyscript/script/Sh84_v2raya.sh" "$hiboyscript/script/Sh84_v2raya.sh"
fi
chmod 777 /etc/storage/script -R

[ "$1" = "del" ] && exit

}

if [ -f /tmp/webui_yes ] ; then
get_www &
get_app $1 &
[ "$1" = "del" ] && exit
fi

