#!/bin/sh
#copyright by hiboy
source /etc/storage/script/init.sh

link="Advanced_Extensions_wifidog.asp"
echo $1
if [ "$1"x = "stop"x ] ; then
    nvram set wifidog_enable=0
    exit
fi

eval 'nvram set tablink'$1'='$link';'

nvram set wifidog_L2="$(($3 + 10))"
nvram set wifidog_L3="$2"
#     show_menu(8,<% nvram_get_x("", "wifidog_L2"); %>,<% nvram_get_x("", "wifidog_L3"); %>);

