#!/bin/bash
#copyright by hiboy
source /etc/storage/script/init.sh

link="Advanced_Extensions_app31.asp"
echo $1
if [ "$1"x = "stop"x ] ; then
    nvram set app_149=0 #zoraxy_enable
    exit
fi

if [ "$1" != "del" ] ; then
eval 'nvram set tablink'$1'='$link';'

nvram set zoraxy_L2="$(($3 + 10))"
nvram set zoraxy_L3="$2"
#     show_menu(8,<% nvram_get_x("", "zoraxy_L2"); %>,<% nvram_get_x("", "zoraxy_L3"); %>);
fi

get_www ()
{

# 加载程序配置页面
mkdir -p /opt/app/zoraxy
if [ -f "/tmp/www_asp/Advanced_Extensions_zoraxyasp" ] ; then
if [ ! -f "/opt/app/zoraxy/Advanced_Extensions_zoraxy.asp" ] ; then
	mv -f /tmp/www_asp/Advanced_Extensions_zoraxyasp /opt/app/zoraxy/Advanced_Extensions_zoraxy.asp
else
	rm -f /tmp/www_asp/Advanced_Extensions_zoraxyasp
fi
fi
if [ ! -f "/opt/app/zoraxy/Advanced_Extensions_zoraxy.asp" ] || [ ! -s "/opt/app/zoraxy/Advanced_Extensions_zoraxy.asp" ] ; then
	wgetcurl.sh /opt/app/zoraxy/Advanced_Extensions_zoraxy.asp "$hiboyfile/Advanced_Extensions_zoraxyasp" "$hiboyfile2/Advanced_Extensions_zoraxyasp"
fi
umount /www/Advanced_Extensions_app31.asp
if [ -f "/opt/app/zoraxy/Advanced_Extensions_zoraxy.asp" ] ; then
	mount --bind /opt/app/zoraxy/Advanced_Extensions_zoraxy.asp /www/Advanced_Extensions_app31.asp
	app31_ver=$(grep 'app31_ver=' /opt/app/zoraxy/Advanced_Extensions_zoraxy.asp | awk -F '=' '{print $2;}')
	nvram set app31_ver=${app31_ver}
fi

}

get_app ()
{

# 更新程序启动脚本
[ "$1" = "del" ] && rm -rf /etc/storage/script/Sh93_zoraxy.sh
if [ ! -f "/etc/storage/script/Sh93_zoraxy.sh" ] || [ ! -s "/etc/storage/script/Sh93_zoraxy.sh" ] ; then
	wgetcurl.sh /etc/storage/script/Sh93_zoraxy.sh "$hiboyscript/script/Sh93_zoraxy.sh" "$hiboyscript/script/Sh93_zoraxy.sh"
fi
chmod 777 /etc/storage/script -R

[ "$1" = "del" ] && exit

}

if [ -f /tmp/webui_yes ] ; then
get_www &
get_app $1 &
[ "$1" = "del" ] && exit
fi

