#!/bin/bash
#copyright by hiboy
source /etc/storage/script/init.sh

link="Advanced_Extensions_app22.asp"
echo $1
if [ "$1"x = "stop"x ] ; then
    nvram set app_123=0 #wxsend_enable
    exit
fi

if [ "$1" != "del" ] ; then
eval 'nvram set tablink'$1'='$link';'

nvram set wxsend_L2="$(($3 + 10))"
nvram set wxsend_L3="$2"
#     show_menu(8,<% nvram_get_x("", "wxsend_L2"); %>,<% nvram_get_x("", "wxsend_L3"); %>);
fi

get_www ()
{

# 加载程序配置页面
mkdir -p /opt/app/wxsend
if [ -f "/tmp/www_asp/Advanced_Extensions_wxsendasp" ] ; then
if [ ! -f "/opt/app/wxsend/Advanced_Extensions_wxsend.asp" ] ; then
	mv -f /tmp/www_asp/Advanced_Extensions_wxsendasp /opt/app/wxsend/Advanced_Extensions_wxsend.asp
else
	rm -f /tmp/www_asp/Advanced_Extensions_wxsendasp
fi
fi
if [ ! -f "/opt/app/wxsend/Advanced_Extensions_wxsend.asp" ] || [ ! -s "/opt/app/wxsend/Advanced_Extensions_wxsend.asp" ] ; then
	wgetcurl.sh /opt/app/wxsend/Advanced_Extensions_wxsend.asp "$hiboyfile/Advanced_Extensions_wxsendasp" "$hiboyfile2/Advanced_Extensions_wxsendasp"
fi
umount /www/Advanced_Extensions_app22.asp
if [ -f "/opt/app/wxsend/Advanced_Extensions_wxsend.asp" ] ; then
	mount --bind /opt/app/wxsend/Advanced_Extensions_wxsend.asp /www/Advanced_Extensions_app22.asp
	app22_ver=$(grep 'app22_ver=' /opt/app/wxsend/Advanced_Extensions_wxsend.asp | awk -F '=' '{print $2;}')
	nvram set app22_ver=${app22_ver}
fi

}

get_app ()
{

# 更新程序启动脚本
[ "$1" = "del" ] && rm -rf /etc/storage/script/Sh45_wx_send.sh
if [ ! -f "/etc/storage/script/Sh45_wx_send.sh" ] || [ ! -s "/etc/storage/script/Sh45_wx_send.sh" ] ; then
	wgetcurl.sh /etc/storage/script/Sh45_wx_send.sh "$hiboyscript/script/Sh45_wx_send.sh" "$hiboyscript/script/Sh45_wx_send.sh"
fi
chmod 777 /etc/storage/script -R
if [ ! -f "/etc/storage/app_30.sh" ] || [ ! -s "/etc/storage/app_30.sh" ] || [ ! -f "/etc/storage/app_31.sh" ] || [ ! -s "/etc/storage/app_31.sh" ] ; then
/etc/storage/script/Sh45_wx_send.sh update_app
fi

[ "$1" = "del" ] && exit

}

if [ -f /tmp/webui_yes ] ; then
get_www &
get_app $1 &
[ "$1" = "del" ] && exit
fi

