#!/bin/bash
#copyright by hiboy
source /etc/storage/script/init.sh

link="Advanced_Extensions_app04.asp"
echo $1
if [ "$1"x = "stop"x ] ; then
    nvram set app_10=0 #printer_enable
    exit
fi

if [ "$1" != "del" ] ; then
eval 'nvram set tablink'$1'='$link';'

nvram set printer_L2="$(($3 + 10))"
nvram set printer_L3="$2"
#     show_menu(8,<% nvram_get_x("", "printer_L2"); %>,<% nvram_get_x("", "printer_L3"); %>);
fi

get_www ()
{

# 加载程序配置页面
mkdir -p /opt/app/printer
if [ -f "/tmp/www_asp/Advanced_Extensions_printerasp" ] ; then
if [ ! -f "/opt/app/printer/Advanced_Extensions_printer.asp" ] ; then
	mv -f /tmp/www_asp/Advanced_Extensions_printerasp /opt/app/printer/Advanced_Extensions_printer.asp
else
	rm -f /tmp/www_asp/Advanced_Extensions_printerasp
fi
fi
if [ ! -f "/opt/app/printer/Advanced_Extensions_printer.asp" ] || [ ! -s "/opt/app/printer/Advanced_Extensions_printer.asp" ] ; then
	wgetcurl.sh /opt/app/printer/Advanced_Extensions_printer.asp "$hiboyfile/Advanced_Extensions_printerasp" "$hiboyfile2/Advanced_Extensions_printerasp"
fi
umount /www/Advanced_Extensions_app04.asp
if [ -f "/opt/app/printer/Advanced_Extensions_printer.asp" ] ; then
	mount --bind /opt/app/printer/Advanced_Extensions_printer.asp /www/Advanced_Extensions_app04.asp
	app4_ver=$(grep 'app4_ver=' /opt/app/printer/Advanced_Extensions_printer.asp | awk -F '=' '{print $2;}')
	nvram set app4_ver=${app4_ver}
fi

}

get_app ()
{

# 更新程序启动脚本
[ "$1" = "del" ] && rm -rf /etc/storage/script/Sh27_printer.sh
if [ ! -f "/etc/storage/script/Sh27_printer.sh" ] || [ ! -s "/etc/storage/script/Sh27_printer.sh" ] ; then
	wgetcurl.sh /etc/storage/script/Sh27_printer.sh "$hiboyscript/script/Sh27_printer.sh" "$hiboyscript/script/Sh27_printer.sh"
fi
chmod 777 /etc/storage/script -R
# 初始配置脚本

[ "$1" = "del" ] && exit

}

if [ -f /tmp/webui_yes ] ; then
get_www &
get_app $1 &
[ "$1" = "del" ] && exit
fi

